### ISSUE TITLE
Support sorting tasks

### ISSUE THREAD

**Issue by sepharg** [Azure/BatchExplorer#1328]
In the Jobs list it´d be good to click on the column names and sort ascending/descending based on that column´s data, specially useful for dates (Created/Started/Completed)

![image](https://user-images.githubusercontent.com/3963438/39691587-5567f72c-51de-11e8-97dd-41552c6c99ae.png)

**Comment by ascobie** [comment]
Hi Daniel,

First off, I agree that this would be very handy to have. The problem we have is that the data is backed by the Batch API and then table storage which in itself doesn't support sorting due to its literally infinite storage capacity.

We could sort client side, but we would only be able to sort the current dataset that we hold in memory. Retrieving and sorting all available data would be too slow. Well it would be possible for smaller datasets, but not large jobs.

Will see what we can come up with.

Andrew


From: Daniel Perez
Sent: Monday, 7 May, 20:06
Subject: [Azure/BatchLabs] Sort Jobs (#1328)
To: Azure/BatchLabs
Cc: Subscribed


I'm submitting a ...
[ ] bug report
[X ] feature request
In the Jobs list it´d be good to click on the column names and sort ascending/descending based on that column´s data, specially useful for dates (Created/Started/Completed)

**Comment by timotheeguerin** [comment]
This has came up many times and as andrew says sorting cannot be done effectively as the backend doesn't support it. However there is case where user might not care or where the data is already loaded.

I propose that maybe we enable client side sorting(Same as the current vm size picker) which shows a warning if not all the data is loaded to let the user know that this might not be the true sorting.

**Comment by sepharg** [comment]
I think that's a good idea, client side sorting is already a good improvement over not having sorting at all
