### ISSUE TITLE
BatchExplorer: Display of Task / Creation Time and Job Duration

### ISSUE THREAD

**Issue by megel** [Azure/BatchExplorer#2067]
There might be a difference between Job duration and Start / Creation time :)

![image](https://user-images.githubusercontent.com/15800069/63689736-12603080-c80b-11e9-831b-02bd735b1e18.png)

**Comment by megel** [comment]
1) the task wasn't rescheduled 
2) no, I guess I opened the job view

**Comment by bgklein** [comment]
I believe what occurred is that due to RunTime being dynamic and the other two fields being static is the following (I have been able to repro a similar behavior on the scale of minutes that hours):

`Page loaded when the task was created 4.9 days ago => As time passes runtime is being continuously updated => Created/Started are not updated when the 'friendly' time becomes 5 days, but since runtime was being continuously updated they are now out of sync`

Refreshing the page likely solves the issue. So don't know if this needs a immediate fix but will keep the issue open for further discussion in the future.

**Comment by megel** [comment]
It's ok for me. This is not a functional problem.
