### ISSUE TITLE
Impossible to verify account and complete login

### ISSUE THREAD

**Issue by rispoli** [Azure/BatchExplorer#2212]
More information is required to verify the account:
![image](https://user-images.githubusercontent.com/2699595/91839077-c1b9b980-ec4e-11ea-89c8-14851dcc11e8.png)
but in the next screen of "Additional security verification", even after filling in all fields, I can't click "Next" and proceed with any of the options:
![image](https://user-images.githubusercontent.com/2699595/91839328-2543e700-ec4f-11ea-9d46-fccba8a25ce1.png)
![image](https://user-images.githubusercontent.com/2699595/91839392-460c3c80-ec4f-11ea-9f76-ebd438aa602e.png)

This goes on even after uninstalling and reinstalling the application, also when deleting the `C:\Users\darispol\AppData\Roaming\BatchExplorer` folder.

Thanks for the help,
Daniele

**Comment by dpwatrous** [comment]
Hi Daniele,

Thanks for such a thorough bug report. I'm able to see the issue as well, but at first glance it looks like the error is happening on the Azure Active Directory authentication page rather than inside Batch Explorer's codebase.

Here's the stack trace I got from the dev tools (from the URL https://account.activedirectory.windowsazure.com/proofup.aspx?culture=en-US)

```
Uncaught ReferenceError: Page_ClientValidate is not defined
    at ValidateStep1 (proofup.aspx?culture=en-US:1255)
    at PerformCurrentStep (proofup.aspx?culture=en-US:1184)
    at HTMLAnchorElement.onclick (proofup.aspx?culture=en-US:4186)
ValidateStep1 @ proofup.aspx?culture=en-US:1255
PerformCurrentStep @ proofup.aspx?culture=en-US:1184
onclick @ proofup.aspx?culture=en-US:4186
VM504:1 Uncaught ReferenceError: WebForm_DoPostBackWithOptions is not defined
    at <anonymous>:1:1
(anonymous) @ VM504:1
```

We'll investigate further and post any updates here.

Regards,
Dave

**Comment by dpwatrous** [comment]
Update: This still looks to me like a bug in AAD authentication, but I figured out a workaround by changing Batch Explorer's User-Agent string to a more standard looking value.
